# Generated by Django 3.2.13 on 2022-05-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(verbose_name=100)),
                ('size', models.IntegerField(verbose_name=100)),
                ('maker', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
            ],
        ),
    ]
